In [1]:
import sys
sys.path.append("..")

In [2]:
import pandas as pd

In [3]:
from src.load_data import load_tables

In [4]:
tables = load_tables()

In [5]:
users = tables['users']
drivers = tables['drivers']
riders = tables['riders']
locations = tables['locations']
trips = pd.read_csv('../src/cleaned_trips.csv')
payments = tables['payments']
reviews = pd.read_csv('../src/cleaned_reviews.csv')
cancellations = tables['cancellations']

### USERS TABLE

In [6]:
users.head()

,user_id,name,email,phone,city,date_joined,is_driver
0,1,David White,david.white@gmail.com,+1-809-169-4853,Houston,2019-09-03,0
1,2,Justin Young,justin.young@icloud.com,+1-808-140-2343,Houston,2022-09-08,1
2,3,Scott Kelly,scott.kelly@icloud.com,+1-523-367-4346,Los Angeles,2020-05-03,0
3,4,Dorothy Phillips,dorothy.phillips@yahoo.com,+1-887-760-5915,Houston,2020-10-09,0
4,5,Barbara Johnson,barbara.johnson@hotmail.com,+1-836-676-2638,New York,2022-01-06,1

1) Which city has more users ?

In [7]:
users['city'].value_counts()

city
Houston        552
Los Angeles    497
New York       480
Chicago        471
Name: count, dtype: int64

2. Out of all the users, how many are drivers?

In [8]:
users['is_driver'].value_counts()

is_driver
0    1600
1     400
Name: count, dtype: int64

### DRIVERS TABLE

In [9]:
import sqlite3 as sql
import pandas as pd

In [10]:
conn = sql.connect('../Data/rideshare.db')

In [11]:
drivers_users = pd.read_sql_query("SELECT * FROM drivers LEFT JOIN users ON users.user_id  = drivers.user_id",conn)
drivers_users.to_csv("../src/drivers_users.csv")
drivers_users.head()

,driver_id,user_id,vehicle_make,vehicle_model,vehicle_year,license_plate,rating,join_date,is_active,user_id,name,email,phone,city,date_joined,is_driver
0,1,1781,Kia,Soul,2015,ZVJ-2140,4.10,2019-12-22,1,1781,Larry Sanders,larry.sanders@yahoo.com,+1-262-831-5244,Los Angeles,2019-02-03,1
1,2,408,Hyundai,Tucson,2016,WLW-3906,4.21,2020-12-14,1,408,Jeffrey Ramirez,jeffrey.ramirez@hotmail.com,+1-474-430-5646,Los Angeles,2022-01-25,1
2,3,693,Hyundai,Sonata,2014,WEA-5140,3.81,2023-07-25,1,693,Kimberly Lewis,kimberly.lewis@icloud.com,+1-399-565-7618,New York,2020-06-18,1
3,4,187,Nissan,Rogue,2021,KDE-9978,4.82,2020-01-11,1,187,David Rogers,david.rogers@protonmail.com,+1-376-140-5059,Houston,2021-06-18,1
4,5,1499,Ford,Fusion,2019,EKJ-8600,3.30,2023-07-15,0,1499,Nicholas Campbell,nicholas.campbell@outlook.com,+1-511-214-2587,New York,2022-10-30,1

1. Which city has Highest Number of drivers ?

In [12]:
drivers_users['city'].value_counts()

city
Houston        110
New York       109
Chicago         91
Los Angeles     90
Name: count, dtype: int64

2. Which vehicle is used mostly by drivers ?

In [13]:
drivers_users['vehicle_make'].value_counts()

vehicle_make
Nissan       50
Chevrolet    48
Mazda        46
Kia          42
Ford         42
Subaru       42
Tesla        38
Toyota       34
Honda        32
Hyundai      26
Name: count, dtype: int64

In [14]:
drivers_users['vehicle_model'].value_counts()

vehicle_model
Equinox       17
Fusion        14
CX-9          13
MX-5          12
Silverado     12
Sentra        12
Crosstrek     11
Altima        11
Sportage      11
Rogue         10
Explorer      10
Maxima        10
Model X       10
Soul           9
Impreza        9
CR-V           9
RAV4           9
Malibu         9
Sorento        9
Pilot          8
Escape         8
Model Y        8
Mazda3         8
Forester       8
Corolla        8
Mustang        8
Cybertruck     8
Legacy         7
Accord         7
Elantra        7
CX-5           7
Model 3        7
Outback        7
Pathfinder     7
Optima         7
Mazda6         6
Santa Fe       6
Camry          6
Prius          6
Traverse       6
Stinger        6
Model S        5
Highlander     5
Ioniq          5
Tucson         4
Sonata         4
Impala         4
Odyssey        4
Civic          4
F-150          2
Name: count, dtype: int64

3. Which vehicle brand has highest rating ?

In [15]:
drivers_users.groupby('vehicle_make')['rating'].mean().sort_values(ascending=False)

vehicle_make
Ford         4.302381
Tesla        4.216053
Subaru       4.170714
Honda        4.170000
Chevrolet    4.158333
Hyundai      4.130000
Nissan       4.127600
Mazda        4.124130
Kia          4.058810
Toyota       4.057941
Name: rating, dtype: float64

4. Which vehicle model has highest rating ?

In [16]:
drivers_users.groupby('vehicle_model')['rating'].mean().sort_values(ascending=False)

vehicle_model
F-150         4.700000
Model X       4.610000
Highlander    4.502000
Crosstrek     4.486364
Tucson        4.445000
Escape        4.435000
Odyssey       4.400000
Maxima        4.397000
Model S       4.380000
Optima        4.330000
Mustang       4.290000
Explorer      4.275000
Equinox       4.250000
Accord        4.248571
CX-9          4.220000
Mazda6        4.218333
Stinger       4.210000
Cybertruck    4.205000
RAV4          4.203333
Fusion        4.196429
Silverado     4.190000
Forester      4.185000
CR-V          4.183333
Rogue         4.178000
Sentra        4.155833
Impala        4.140000
Outback       4.138571
Ioniq         4.112000
MX-5          4.109167
Malibu        4.090000
Elantra       4.088571
Legacy        4.085714
CX-5          4.082857
Sorento       4.072222
Sonata        4.070000
Soul          4.067778
Pilot         4.062500
Camry         4.048333
Altima        4.026364
Santa Fe      4.023333
Civic         3.987500
Mazda3        3.956250
Traverse      3.950000
Model 3       3.934286
Model Y       3.878750
Impreza       3.863333
Corolla       3.858750
Sportage      3.785455
Pathfinder    3.781429
Prius         3.745000
Name: rating, dtype: float64

5. Which city has highest driver ratings ?

In [17]:
drivers_users.groupby('city')['rating'].mean().sort_values(ascending=False)

city
New York       4.194404
Chicago        4.171978
Los Angeles    4.123444
Houston        4.118909
Name: rating, dtype: float64

6. How many drivers are active ?

In [18]:
drivers_users['is_active'].value_counts()

is_active
1    351
0     49
Name: count, dtype: int64

### RIDERS TABLE

In [19]:
riders_users = pd.merge(riders,users,on='user_id',how='left')
riders_users.to_csv("../src/riders_users.csv")
riders_users.head()

,rider_id,user_id,rating,total_trips,created_at,name,email,phone,city,date_joined,is_driver
0,1,1958,4.66,1,2020-09-13 01:52:12,Catherine Perez,catherine.perez@protonmail.com,+1-599-361-7601,New York,2022-09-15,0
1,2,373,3.76,2,2019-11-03 13:23:24,Diane Peterson,diane.peterson@icloud.com,+1-794-804-4621,Houston,2021-02-05,0
2,3,680,3.03,8,2020-01-23 08:54:39,Stephen Parker,stephen.parker@icloud.com,+1-574-726-5514,Houston,2023-03-27,0
3,4,1190,3.31,1,2019-11-06 23:53:19,Timothy Lee,timothy.lee@protonmail.com,+1-499-825-8233,Houston,2023-02-09,0
4,5,1970,3.71,36,2023-09-17 01:02:59,Scott James,scott.james@hotmail.com,+1-628-520-4094,New York,2022-06-21,0

1. Which city has the highest rider ratings ?

In [20]:
riders_users.groupby('city')['rating'].mean().sort_values(ascending=False)

city
New York       4.001321
Los Angeles    3.999803
Houston        3.995181
Chicago        3.967211
Name: rating, dtype: float64

2. Which city has the highest riders ?

In [21]:
riders_users['city'].value_counts()

city
Houston        442
Los Angeles    407
Chicago        380
New York       371
Name: count, dtype: int64

### LOCATIONS TABLE

In [22]:
locations.head()

   location_id          zone_name      city  latitude  longitude    zone_type
0            1       Times Square  New York   40.7580   -73.9855   commercial
1            2        JFK Airport  New York   40.6413   -73.7781      airport
2            3  LaGuardia Airport  New York   40.7769   -73.8740      airport
3            4   Brooklyn Heights  New York   40.6960   -73.9946  residential
4            5             Harlem  New York   40.8116   -73.9465  residential

1. Which zone type has the highest number of locations?

In [23]:
locations['zone_type'].value_counts()

zone_type
residential    16
commercial     13
airport         7
transit_hub     4
Name: count, dtype: int64

2. How many locations are present in each city?

In [24]:
locations['city'].value_counts()

city
New York       10
Chicago        10
Los Angeles    10
Houston        10
Name: count, dtype: int64

### TRIPS TABLE

In [25]:
trips.head()

,trip_id,rider_id,driver_id,pickup_location_id,dropoff_location_id,requested_at,started_at,completed_at,status,distance_km,duration_mins,base_fare,surge_multiplier,total_fare,payment_method
0,1,1,34,26,29,2024-06-24 12:20:11,2024-06-24 12:29:11,2024-06-24 14:24:11,completed,39.14,115,68.55,1.00,68.55,wallet
1,3,2,126,13,15,2023-08-17 09:30:06,2023-08-17 09:32:06,2023-08-17 09:36:06,completed,2.78,4,6.36,1.00,6.36,wallet
2,4,2,255,10,6,2022-11-21 09:53:31,2022-11-21 09:58:31,2022-11-21 10:17:31,completed,14.25,19,21.98,1.00,21.98,cash
3,5,3,186,37,31,2022-01-15 14:04:56,2022-01-15 14:12:56,2022-01-15 14:56:56,completed,41.54,44,56.99,1.00,56.99,wallet
4,6,3,370,18,14,2022-05-05 07:41:36,2022-05-05 07:53:36,2022-05-05 08:33:36,completed,22.63,40,35.39,1.57,55.56,cash

1. What is the distribution of trip statuses?

In [26]:
trips['status'].value_counts()

status
completed    16827
Name: count, dtype: int64

2. What are the average distance and duration of trips?

In [27]:
trips[['distance_km','duration_mins']].mean()

distance_km      18.018348
duration_mins    31.371011
dtype: float64

### PAYMENTS TABLE

In [28]:
payments.head()

   payment_id  trip_id  amount  method   status              paid_at
0           1        1   68.55  wallet  success  2024-06-24 14:24:15
1           2        3    6.36  wallet  success  2023-08-17 09:36:16
2           3        4   21.98    cash  success  2022-11-21 10:17:36
3           4        5   56.99  wallet  success  2022-01-15 14:57:02
4           5        6   55.56    cash  success  2022-05-05 08:34:02

1. which is the most preferred payment method ?

In [29]:
trips['payment_method'].value_counts()

payment_method
card      5700
wallet    5621
cash      5506
Name: count, dtype: int64

### REVIEWS TABLE

In [30]:
reviews.head()

,Unnamed: 0,review_id,trip_id,reviewer_id,reviewee_id,rating,comment,reviewed_at
0,0,1,1,1958,1001,4,Very comfortable ride.,2024-06-24 14:52:11
1,1,2,1,1001,1958,4,Super friendly and helpful.,2024-06-24 16:09:11
2,2,3,3,324,373,4,Very clean car.,2023-08-17 11:08:06
3,6,7,13,553,680,3,"Great driver, very professional!",2023-06-27 01:25:43
4,7,8,14,680,1649,3,Fine driver.,2024-03-17 22:45:46

1. What is the average rating?

In [33]:
reviews['rating'].value_counts()

rating
4    3606
3    3298
5    1399
2     850
1      63
Name: count, dtype: int64

2. How many reviews contain comments?

In [37]:
r = tables['reviews']
r['comment'].notna().sum()

np.int64(9216)

### CANCELLATIONS TABLE

In [38]:
cancellations.head()

   cancel_id  trip_id cancelled_by                reason         cancelled_at
0          1        2       driver    personal emergency  2024-01-25 20:55:28
1          2        7       driver          wrong pickup  2023-06-02 19:32:48
2          3       16       driver  rider rating too low  2022-05-13 15:56:17
3          4       29       driver  rider rating too low  2022-03-06 04:48:56
4          5       63        rider    personal emergency  2022-07-14 23:33:56

1. Who cancels trips more often — riders or drivers?

In [39]:
cancellations['cancelled_by'].value_counts()

cancelled_by
rider     2069
driver     897
Name: count, dtype: int64

2. What are the most common cancellation reasons?

In [40]:
cancellations['reason'].value_counts()

reason
personal emergency      396
too long wait           284
changed my mind         283
waited too long         262
price too high          250
duplicate booking       249
found another ride      248
driver too far          231
wrong pickup            137
system error            133
area not safe           133
vehicle issue           128
rider rating too low    124
rider unresponsive      108
Name: count, dtype: int64