In [1]:
import sqlite3 as sql
import pandas as pd

In [5]:
conn = sql.connect('../Data/rideshare.db')

### List Table Names FROM rideshare.db

In [6]:
tables = conn.execute ("SELECT name FROM sqlite_master WHERE type='table';")

In [7]:
for row in tables:
    print(row)

('users',)
('drivers',)
('riders',)
('locations',)
('trips',)
('payments',)
('reviews',)
('cancellations',)

### LOAD TABLES INTO PANDAS DATA FRAME

In [12]:
users = pd.read_sql_query("SELECT * FROM users",conn)
users.head()

,user_id,name,email,phone,city,date_joined,is_driver
0,1,David White,david.white@gmail.com,+1-809-169-4853,Houston,2019-09-03,0
1,2,Justin Young,justin.young@icloud.com,+1-808-140-2343,Houston,2022-09-08,1
2,3,Scott Kelly,scott.kelly@icloud.com,+1-523-367-4346,Los Angeles,2020-05-03,0
3,4,Dorothy Phillips,dorothy.phillips@yahoo.com,+1-887-760-5915,Houston,2020-10-09,0
4,5,Barbara Johnson,barbara.johnson@hotmail.com,+1-836-676-2638,New York,2022-01-06,1

In [13]:
drivers = pd.read_sql_query("SELECT * FROM drivers",conn)
drivers.head()

,driver_id,user_id,vehicle_make,vehicle_model,vehicle_year,license_plate,rating,join_date,is_active
0,1,1781,Kia,Soul,2015,ZVJ-2140,4.10,2019-12-22,1
1,2,408,Hyundai,Tucson,2016,WLW-3906,4.21,2020-12-14,1
2,3,693,Hyundai,Sonata,2014,WEA-5140,3.81,2023-07-25,1
3,4,187,Nissan,Rogue,2021,KDE-9978,4.82,2020-01-11,1
4,5,1499,Ford,Fusion,2019,EKJ-8600,3.30,2023-07-15,0

In [14]:
riders = pd.read_sql_query("SELECT * FROM riders",conn)
riders.head()

   rider_id  user_id  rating  total_trips           created_at
0         1     1958    4.66            1  2020-09-13 01:52:12
1         2      373    3.76            2  2019-11-03 13:23:24
2         3      680    3.03            8  2020-01-23 08:54:39
3         4     1190    3.31            1  2019-11-06 23:53:19
4         5     1970    3.71           36  2023-09-17 01:02:59

In [15]:
locations = pd.read_sql_query("SELECT * FROM locations",conn)
locations.head()

   location_id          zone_name      city  latitude  longitude    zone_type
0            1       Times Square  New York   40.7580   -73.9855   commercial
1            2        JFK Airport  New York   40.6413   -73.7781      airport
2            3  LaGuardia Airport  New York   40.7769   -73.8740      airport
3            4   Brooklyn Heights  New York   40.6960   -73.9946  residential
4            5             Harlem  New York   40.8116   -73.9465  residential

In [16]:
trips = pd.read_sql_query("SELECT * FROM trips",conn)
trips.head()

,trip_id,rider_id,driver_id,pickup_location_id,dropoff_location_id,requested_at,started_at,completed_at,status,distance_km,duration_mins,base_fare,surge_multiplier,total_fare,payment_method
0,1,1,34,26,29,2024-06-24 12:20:11,2024-06-24 12:29:11,2024-06-24 14:24:11,completed,39.14,115,68.55,1.0,68.55,wallet
1,2,2,185,18,12,2024-01-25 20:52:28,2024-01-25 20:54:28,NaN,cancelled,9.53,22,17.38,1.0,17.38,wallet
2,3,2,126,13,15,2023-08-17 09:30:06,2023-08-17 09:32:06,2023-08-17 09:36:06,completed,2.78,4,6.36,1.0,6.36,wallet
3,4,2,255,10,6,2022-11-21 09:53:31,2022-11-21 09:58:31,2022-11-21 10:17:31,completed,14.25,19,21.98,1.0,21.98,cash
4,5,3,186,37,31,2022-01-15 14:04:56,2022-01-15 14:12:56,2022-01-15 14:56:56,completed,41.54,44,56.99,1.0,56.99,wallet

In [17]:
payments = pd.read_sql_query("SELECT * FROM payments",conn)
payments.head()

   payment_id  trip_id  amount  method   status              paid_at
0           1        1   68.55  wallet  success  2024-06-24 14:24:15
1           2        3    6.36  wallet  success  2023-08-17 09:36:16
2           3        4   21.98    cash  success  2022-11-21 10:17:36
3           4        5   56.99  wallet  success  2022-01-15 14:57:02
4           5        6   55.56    cash  success  2022-05-05 08:34:02

In [18]:
reviews = pd.read_sql_query("SELECT * FROM  payments",conn)
reviews.head()

   payment_id  trip_id  amount  method   status              paid_at
0           1        1   68.55  wallet  success  2024-06-24 14:24:15
1           2        3    6.36  wallet  success  2023-08-17 09:36:16
2           3        4   21.98    cash  success  2022-11-21 10:17:36
3           4        5   56.99  wallet  success  2022-01-15 14:57:02
4           5        6   55.56    cash  success  2022-05-05 08:34:02

In [19]:
cancellations = pd.read_sql_query("SELECT * FROM cancellations",conn)
cancellations.head()

   cancel_id  trip_id cancelled_by                reason         cancelled_at
0          1        2       driver    personal emergency  2024-01-25 20:55:28
1          2        7       driver          wrong pickup  2023-06-02 19:32:48
2          3       16       driver  rider rating too low  2022-05-13 15:56:17
3          4       29       driver  rider rating too low  2022-03-06 04:48:56
4          5       63        rider    personal emergency  2022-07-14 23:33:56