In [4]:
import sys
sys.path.append("..")

In [5]:
from src.load_data import load_tables

In [6]:
tables = load_tables()

In [8]:
users = tables['users']
drivers = tables['drivers']
riders = tables['riders']
locations = tables['locations']
trips = tables['trips']
payments = tables['payments']
reviews = tables['reviews']
cancellations = tables['cancellations']

## UNDERSTANDING THE DATA

### USERS TABLE
- Number of Rows : 2000
- Number of Columns : 7
- Missing Values : None
- Duplicate Rows : None

In [10]:
users.shape

(2000, 7)

In [11]:
users.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   user_id      2000 non-null   int64
 1   name         2000 non-null   str
 2   email        2000 non-null   str
 3   phone        2000 non-null   str
 4   city         2000 non-null   str
 5   date_joined  2000 non-null   str
 6   is_driver    2000 non-null   int64
dtypes: int64(2), str(5)
memory usage: 109.5 KB

In [17]:
users.describe(include='all')

,user_id,name,email,phone,city,date_joined,is_driver
count,2000.000000,2000,2000,2000,2000,2000,2000.0000
unique,NaN,1764,2000,2000,4,1243,NaN
top,NaN,Diane Hughes,david.white@gmail.com,+1-809-169-4853,Houston,2021-12-07,NaN
freq,NaN,3,1,1,552,7,NaN
mean,1000.500000,NaN,NaN,NaN,NaN,NaN,0.2000
std,577.494589,NaN,NaN,NaN,NaN,NaN,0.4001
min,1.000000,NaN,NaN,NaN,NaN,NaN,0.0000
25%,500.750000,NaN,NaN,NaN,NaN,NaN,0.0000
50%,1000.500000,NaN,NaN,NaN,NaN,NaN,0.0000
75%,1500.250000,NaN,NaN,NaN,NaN,NaN,0.0000
max,2000.000000,NaN,NaN,NaN,NaN,NaN,1.0000

In [13]:
users.isnull().sum()

user_id        0
name           0
email          0
phone          0
city           0
date_joined    0
is_driver      0
dtype: int64

In [14]:
users.duplicated().sum()

np.int64(0)

### DRIVERS TABLE
- Number of Rows : 400
- Number of Columns : 9
- Missing Values : None
- Duplicate Rows : None

In [15]:
drivers.shape

(400, 9)

In [16]:
drivers.info()

<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   driver_id      400 non-null    int64
 1   user_id        400 non-null    int64
 2   vehicle_make   400 non-null    str
 3   vehicle_model  400 non-null    str
 4   vehicle_year   400 non-null    int64
 5   license_plate  400 non-null    str
 6   rating         400 non-null    float64
 7   join_date      400 non-null    str
 8   is_active      400 non-null    int64
dtypes: float64(1), int64(4), str(4)
memory usage: 28.3 KB

In [18]:
drivers.describe(include='all')

,driver_id,user_id,vehicle_make,vehicle_model,vehicle_year,license_plate,rating,join_date,is_active
count,400.000000,400.00000,400,400,400.000000,400,400.000000,400,400.000000
unique,NaN,NaN,10,50,NaN,400,NaN,348,NaN
top,NaN,NaN,Nissan,Equinox,NaN,ZVJ-2140,NaN,2019-12-19,NaN
freq,NaN,NaN,50,17,NaN,1,NaN,3,NaN
mean,200.500000,995.78500,NaN,NaN,2017.530000,NaN,4.152575,NaN,0.877500
std,115.614301,588.38962,NaN,NaN,3.521378,NaN,0.532396,NaN,0.328273
min,1.000000,2.00000,NaN,NaN,2012.000000,NaN,2.590000,NaN,0.000000
25%,100.750000,468.50000,NaN,NaN,2014.000000,NaN,3.770000,NaN,1.000000
50%,200.500000,1017.00000,NaN,NaN,2018.000000,NaN,4.180000,NaN,1.000000
75%,300.250000,1497.50000,NaN,NaN,2020.250000,NaN,4.610000,NaN,1.000000
max,400.000000,1999.00000,NaN,NaN,2023.000000,NaN,5.000000,NaN,1.000000

In [19]:
drivers.isnull().sum()

driver_id        0
user_id          0
vehicle_make     0
vehicle_model    0
vehicle_year     0
license_plate    0
rating           0
join_date        0
is_active        0
dtype: int64

In [20]:
drivers.duplicated().sum()

np.int64(0)

### RIDERS TABLE
- Number of Rows : 1600
- Number of Columns : 5
- Missing Values : None
- Duplicate Rows : None

In [21]:
riders.shape

(1600, 5)

In [22]:
riders.info()

<class 'pandas.DataFrame'>
RangeIndex: 1600 entries, 0 to 1599
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   rider_id     1600 non-null   int64
 1   user_id      1600 non-null   int64
 2   rating       1600 non-null   float64
 3   total_trips  1600 non-null   int64
 4   created_at   1600 non-null   str
dtypes: float64(1), int64(3), str(1)
memory usage: 62.6 KB

In [23]:
riders.describe(include='all')

          rider_id      user_id       rating  total_trips           created_at
count   1600.00000  1600.000000  1600.000000  1600.000000                 1600
unique         NaN          NaN          NaN          NaN                 1600
top            NaN          NaN          NaN          NaN  2020-09-13 01:52:12
freq           NaN          NaN          NaN          NaN                    1
mean     800.50000  1001.678750     3.991137    10.516875                  NaN
std      462.02453   574.919114     0.590380    17.336344                  NaN
min        1.00000     1.000000     3.000000     0.000000                  NaN
25%      400.75000   515.500000     3.450000     1.000000                  NaN
50%      800.50000   998.500000     3.990000     3.000000                  NaN
75%     1200.25000  1501.250000     4.500000    13.000000                  NaN
max     1600.00000  2000.000000     5.000000    94.000000                  NaN

In [24]:
riders.isnull().sum()

rider_id       0
user_id        0
rating         0
total_trips    0
created_at     0
dtype: int64

In [25]:
riders.duplicated().sum()

np.int64(0)